### ISSUE TITLE
No escaping mechanism available for texts containing brackets

### ISSUE THREAD

**Issue by phochste** [nichtich/RDF-aREF#18]
The decoding of JSON files containing brackets doesn't always work:

    dct_description => 'Photon emission x < 1'    # works

    dct_description => '< Life in Brackets >'  # generates invalid IRI exception

The source of the behavior is in  RDF::aREF::Decoder

    35: use constant explicitIRIlike => qr/^<(.+)>$/;

**Comment by nichtich** [comment]
aREF does not include a full URI syntax check, so all strings enclosed in `<` and `>` must be URIs. Append `@` to make it a plain literal:

    dct_description => '< Life in Brackets >@'

**Comment by phochste** [comment]
ok thx
